import { vi } from "vitest";
import { sampleParamsFull } from "../fixtures/sample-params";

/**
 * A fake `Env` for the service-layer suites.
 *
 * Lives beside the services it serves, exactly as `repository/test-db.ts` lives
 * beside the repository, so every suite that needs an `Env` shares one
 * definition instead of assembling its own.
 *
 * This file holds one of the two casts in the app (AGENTS.md §4). `Env` is
 * generated by `wrangler types` and describes the full Workers runtime — the
 * `Ai` binding, a whole `KVNamespace`, an `R2Bucket`, a `D1Database` — none of
 * which can be constructed outside a Worker. Unlike `cors.ts` and `config.ts`,
 * the pipeline cannot be narrowed to a smaller structural type: `planConcept`
 * and `colorizeMotif` take the real `Env` because iris-08 and iris-09 replace
 * their bodies with calls that reach `env.AI`, and narrowing now would only have
 * to be widened again then.
 *
 * `AI.run` is a fake that returns a plausible structured reply for text calls
 * (`@cf/openai/gpt-oss-120b`) and throws for image calls
 * (`@cf/black-forest-labs/...`). The image call is still faked at this point
 * and must stay unbillable — iris-09 replaces this throw with the real image
 * generation.
 *
 * The two gateway fields are overridable because `readGatewayCost` is the one
 * service that reads them and needs them to differ per test: `aiGatewayLogId`
 * decides whether it calls the gateway at all, and `getLog` is what it retries
 * against. Overriding them here rather than assembling a second `Env` in
 * `gatewayCost.test.ts` is the whole reason this file exists — a local fake
 * there would mean a third cast in an app whose count is stated two paragraphs
 * up.
 *
 * @param overrides - `aiGatewayLogId` defaults to `""`, which is the value a
 *   call that never routed through the gateway leaves behind. `getLog` defaults
 *   to a mock nothing calls.
 */
export function fakeEnv(overrides: { aiGatewayLogId?: string | null; getLog?: ReturnType<typeof vi.fn> } = {}) {
	const run = vi.fn(async (model: string) => {
		if (model.startsWith("@cf/black-forest-labs")) {
			throw new Error("AI.run: image call not faked yet (iris-09)");
		}
		return {
			choices: [{ message: { content: JSON.stringify(sampleParamsFull) } }],
			usage: { prompt_tokens: 100, completion_tokens: 50 },
		};
	});

	const patternsPut = vi.fn().mockResolvedValue({});

	const getLog = overrides.getLog ?? vi.fn();
	const gateway = vi.fn().mockReturnValue({ getLog });

	const env = {
		AI: { run, gateway, aiGatewayLogId: overrides.aiGatewayLogId ?? "" },
		AI_GATEWAY_ID: "",
		// Empty KV → every value resolves from the vars below.
		CONFIG: { get: vi.fn().mockResolvedValue(new Map<string, string | null>()) },
		PATTERNS: { put: patternsPut, get: vi.fn() },
		DB: {},
		PLANNER_MODEL: "@cf/openai/gpt-oss-120b",
		IMAGE_MODEL: "@cf/black-forest-labs/flux-2-klein-9b",
		MAX_RETRIES: "2",
		RETENTION_LIMIT: "5",
		MAX_RESUME_ATTEMPTS: "3",
	} as unknown as Env;

	return { env, run, patternsPut, getLog };
}
