import { vi } from "vitest";

/**
 * A fake `Env` for the service-layer suites.
 *
 * Lives beside the services it serves, exactly as `repository/test-db.ts` lives
 * beside the repository, so every suite that needs an `Env` shares one
 * definition instead of assembling its own.
 *
 * **This file holds one of the two casts in the app** (AGENTS.md §4). `Env` is
 * generated by `wrangler types` and describes the full Workers runtime — the
 * `Ai` binding, a whole `KVNamespace`, an `R2Bucket`, a `D1Database` — none of
 * which can be constructed outside a Worker. Unlike `cors.ts` and `config.ts`,
 * the pipeline cannot be narrowed to a smaller structural type: `planConcept`
 * and `colorizeMotif` take the real `Env` because iris-08 and iris-09 replace
 * their bodies with calls that reach `env.AI`, and narrowing now would only have
 * to be widened again then.
 *
 * `AI.run` is a fake that **throws if called**. Nothing in iris-05 reaches a
 * model, and a test that would silently start billing the day iris-08 lands is
 * worse than no test at all.
 */
export function fakeEnv() {
	const run = vi.fn(async () => {
		throw new Error("AI.run must never be called by the fakes in iris-05");
	});

	const patternsPut = vi.fn().mockResolvedValue({});

	const env = {
		AI: { run, gateway: vi.fn(), aiGatewayLogId: null },
		AI_GATEWAY_ID: "iris",
		// Empty KV → every value resolves from the vars below.
		CONFIG: { get: vi.fn().mockResolvedValue(new Map<string, string | null>()) },
		PATTERNS: { put: patternsPut, get: vi.fn() },
		DB: {},
		PLANNER_MODEL: "@cf/openai/gpt-oss-120b",
		IMAGE_MODEL: "@cf/black-forest-labs/flux-2-klein-9b",
		MAX_RETRIES: "2",
		RETENTION_LIMIT: "5",
		MAX_RESUME_ATTEMPTS: "3",
	} as unknown as Env;

	return { env, run, patternsPut };
}
