import { vi } from "vitest";
import { sampleParamsFull, SAMPLE_IMAGE_BASE64 } from "../fixtures/sample-params";
import { createFailingD1, createTestD1 } from "../repository/test-db";

/**
 * What the fake gateway log reports a call cost.
 *
 * Exported so a suite asserting on a cost references this rather than repeating
 * the number. The two helpers this file replaced had drifted to two different
 * values for no reason anyone recorded.
 */
export const GATEWAY_COST_USD = 0.0019008;

/** The runtime config vars `resolveConfig` falls back to when KV is empty. */
const VARS = {
	PLANNER_MODEL: "@cf/openai/gpt-oss-120b",
	// Empty by default, so `plannerModelFor` falls back to PLANNER_MODEL and every
	// existing suite keeps calling the model it always did. A test that wants the
	// multimodal path opts in with the `visionPlannerModel` override.
	VISION_PLANNER_MODEL: "",
	IMAGE_MODEL: "@cf/black-forest-labs/flux-1-schnell",
	// Set, matching wrangler.jsonc, so a suite that attaches a reference image
	// exercises the multipart path rather than `imageModelFor`'s refusal. The
	// refusal has its own test in `config.test.ts`, where it is the subject
	// rather than an accident of the fake.
	IMAGE_TO_IMAGE_MODEL: "@cf/black-forest-labs/flux-2-klein-9b",
	AI_GATEWAY_ID: "helios",
	MAX_RETRIES: "2",
	RETENTION_LIMIT: "5",
	MAX_RESUME_ATTEMPTS: "3",
	// Empty by default, exactly like VISION_PLANNER_MODEL above and for the same
	// reason: `researchModelFor` reads it as "retrieval off", so every existing
	// suite keeps making the calls it always did. A suite that wants the research
	// stage opts in rather than every other suite opting out.
	RESEARCH_MODEL: "",
	CLASSIFIER_MODEL: "@cf/meta/llama-4-scout-17b-16e-instruct",
	MAX_TOOL_ITERATIONS: "3",
	MAX_SEARCH_RESULTS: "5",
	MIN_CHUNK_CHARS: "200",
	SEARCH_MATCH_THRESHOLD: "0.5",
	AI_SEARCH_QUERY_REWRITE: "false",
};

/**
 * A fake `Env` for the service-layer suites.
 *
 * Lives beside the services it serves, exactly as `repository/test-db.ts` lives
 * beside the repository, so every suite that needs an `Env` shares one
 * definition instead of assembling its own. It replaces four near-duplicate
 * `fakeEnv` helpers that had quietly drifted apart: two different gateway costs,
 * two different default log ids, one `AI.run` that dispatched on model name and
 * one that ignored it, and — the one that mattered — one `DB` that threw and one
 * that silently answered every query with nothing.
 *
 * `cors.test.ts` and `config.test.ts` deliberately do **not** use this. Their
 * subjects take the narrowed `CorsEnv` and `ConfigEnv` structural types, so they
 * build real values and need no fake `Env` and no cast at all.
 *
 * This file holds one of the four casts in the app (AGENTS.md §4). `Env` is
 * generated by `wrangler types` and describes the full Workers runtime — the
 * `Ai` binding, a whole `KVNamespace`, an `R2Bucket`, a `D1Database` — none of
 * which can be constructed outside a Worker. Unlike `cors.ts` and `config.ts`,
 * the pipeline cannot be narrowed to a smaller structural type: `planConcept`
 * and the image generator take the real `Env` because they reach `env.AI`.
 *
 * `DB` is a **real** in-memory D1 (`createTestD1`), not a stub that answers
 * every query with `[]`. `exportAndPrune` swallows everything it catches, by
 * design — an audit concern must not cost a caller the result they already paid
 * for — so a fake that cannot write turns an export failure into a passing test.
 * `throwingD1` is the deliberate opposite, for the tests that prove the swallow
 * is still there.
 *
 * @param overrides - `planner` and `image` replace the default model replies, or
 *   throw when given an `Error`. `aiGatewayLogId` defaults to `"log-1"`; pass
 *   `null` for a call that never routed through the gateway. `getLog` lets a
 *   caller inject its own spy, which is what `gatewayCost.test.ts` needs since
 *   the log read is its whole subject.
 */
export function fakeEnv(
	overrides: {
		planner?: unknown | Error;
		classifier?: unknown | Error;
		image?: unknown | Error;
		getLog?: ReturnType<typeof vi.fn>;
		aiGatewayLogId?: string | null;
		maxRetries?: number;
		maxResumeAttempts?: number;
		/** Turns the vision planner on for this env. Empty (the default) leaves it
		 *  off and `plannerModelFor` falls back to `PLANNER_MODEL`. */
		visionPlannerModel?: string;
		patternsPut?: "ok" | "fail";
		throwingD1?: boolean;
	} = {},
) {
	const vars = {
		...VARS,
		...(overrides.maxRetries !== undefined ? { MAX_RETRIES: String(overrides.maxRetries) } : {}),
		...(overrides.maxResumeAttempts !== undefined
			? { MAX_RESUME_ATTEMPTS: String(overrides.maxResumeAttempts) }
			: {}),
		...(overrides.visionPlannerModel !== undefined
			? { VISION_PLANNER_MODEL: overrides.visionPlannerModel }
			: {}),
	};

	// All three parameters are declared, and the return is `unknown`, because
	// that is `Ai.run`'s real shape. Letting the signature be inferred from the
	// body narrows it to one argument and one of two literal reply shapes, and a
	// test that reads `run.mock.calls[0][2]` or queues a different reply then
	// fails to compile against a fake that is merely under-described.
	const run = vi.fn(async (model: string, _input?: unknown, _options?: unknown): Promise<unknown> => {
		// Either planner id answers with a planner reply. Matching only
		// `PLANNER_MODEL` would send a vision-model call down the image branch and
		// return an image where the suite expected params.
		if (model === vars.PLANNER_MODEL || (vars.VISION_PLANNER_MODEL !== "" && model === vars.VISION_PLANNER_MODEL)) {
			if (overrides.planner instanceof Error) throw overrides.planner;
			return overrides.planner ?? { response: JSON.stringify(sampleParamsFull), usage: { neurons: 102 } };
		}
		// Before the image fall-through, because the fall-through is a catch-all
		// and a catch-all is how a new model id gets an image back where the suite
		// expected JSON. Every stage added after this one has the same problem and
		// needs the same branch — the last `if` here answers for models nobody has
		// taught it about.
		if (model === vars.CLASSIFIER_MODEL) {
			if (overrides.classifier instanceof Error) throw overrides.classifier;
			return (
				overrides.classifier ?? { response: JSON.stringify({ mode: "tile" }), usage: { neurons: 8 } }
			);
		}
		if (overrides.image instanceof Error) throw overrides.image;
		return overrides.image ?? { image: SAMPLE_IMAGE_BASE64 };
	});

	const getLog = overrides.getLog ?? vi.fn().mockResolvedValue({ cost: GATEWAY_COST_USD });
	const gateway = vi.fn().mockReturnValue({ getLog });

	const patternsPut = vi.fn().mockResolvedValue({});
	if (overrides.patternsPut === "fail") patternsPut.mockRejectedValue(new Error("r2 down"));

	const d1 = overrides.throwingD1 ? createFailingD1() : createTestD1();

	const env = {
		// `!== undefined`, not `??`: `null` is a meaningful value here — it is what a
		// call that never routed through the gateway leaves behind, and `??` would
		// quietly turn that case back into a live log id.
		AI: { run, gateway, aiGatewayLogId: overrides.aiGatewayLogId !== undefined ? overrides.aiGatewayLogId : "log-1" },
		AI_GATEWAY_ID: vars.AI_GATEWAY_ID,
		// Empty KV → every value resolves from the vars below.
		CONFIG: { get: vi.fn().mockResolvedValue(new Map<string, string | null>()) },
		PATTERNS: { put: patternsPut, get: vi.fn() },
		DB: d1,
		PLANNER_MODEL: vars.PLANNER_MODEL,
		VISION_PLANNER_MODEL: vars.VISION_PLANNER_MODEL,
		IMAGE_MODEL: vars.IMAGE_MODEL,
		IMAGE_TO_IMAGE_MODEL: vars.IMAGE_TO_IMAGE_MODEL,
		MAX_RETRIES: vars.MAX_RETRIES,
		RETENTION_LIMIT: vars.RETENTION_LIMIT,
		MAX_RESUME_ATTEMPTS: vars.MAX_RESUME_ATTEMPTS,
		RESEARCH_MODEL: vars.RESEARCH_MODEL,
		CLASSIFIER_MODEL: vars.CLASSIFIER_MODEL,
		MAX_TOOL_ITERATIONS: vars.MAX_TOOL_ITERATIONS,
		MAX_SEARCH_RESULTS: vars.MAX_SEARCH_RESULTS,
		MIN_CHUNK_CHARS: vars.MIN_CHUNK_CHARS,
		SEARCH_MATCH_THRESHOLD: vars.SEARCH_MATCH_THRESHOLD,
		AI_SEARCH_QUERY_REWRITE: vars.AI_SEARCH_QUERY_REWRITE,
	} as unknown as Env;

	// `d1` comes back so a suite can read what the export actually wrote, which
	// is the only way an assertion can tell an export from a swallowed failure.
	return { env, run, gateway, getLog, patternsPut, d1, vars };
}
